name: bitroot
description: "Demo app for project view"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
# Using Android Studio Koala | 2024.1.1 Patch 1
# Windows 10 system
# Flutter version: 3.22.3 stable
# Java JDK-17 or JDK-22

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  http: ^1.2.2
  lottie: ^3.1.2
  flutter_bloc: ^8.1.6
  rxdart: ^0.28.0
  equatable: ^2.0.5
  collection: ^1.19.0
  skeletonizer: ^1.4.2
  flutter_localization: ^0.2.0
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.8
  platform_info: ^5.0.0
  url_strategy: ^0.3.0
  animations: ^2.0.11
  dotted_line: ^3.2.2
  flutter_spinkit: ^5.2.1
  internet_connection_checker:


dependency_overrides:
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/locale/
    - assets/images/
    - assets/lottie/
